### ISSUE TITLE
[Documentation]: Blog Endpoints

### ISSUE THREAD

**Issue by devffery** [hngprojects/hng_boilerplate_expressjs#159]
**Description:**
We need to create comprehensive documentation for the blog endpoints of our API. The documentation should be written in Swagger (OpenAPI) format and should cover the following endpoints:

1. **Create Blog Post**
   - Method: `POST`
   - Endpoint: `/api/v1/blog`
   - Description: Allow user to create a blog post.
   - Request Body: 
     ```yaml
     BlogInput:
       type: object
       properties:
         title:
           type: string
           description: Title of the blog post
         content:
           type: string
           description: Content of the blog post
         author:
           type: string
           description: Author of the blog post
         categories:
           type: array
           items:
             type: string
           description: Categories of the blog post
         Imageurl:
           type: string
           description: URL of the blog post image
         tags:
           type: array
           items:
             type: string
           description: Tags of the blog post
       required:
         - title
         - content
         - author
     ```
   - Responses:
     - `201`: Blog post created successfully
     - `400`: Bad request
     - `500`: Server error

2. **Get All Blog Posts with Pagination**
   - Method: `GET`
   - Endpoint: `/api/v1/blogs`
   - Description: Allow user to get all blog posts with pagination (page, limit, offset).
   - Parameters:
     - `page`: integer (optional, default: 1)
     - `limit`: integer (optional, default: 10)
     - `offset`: integer (optional, default: 0)
   - Responses:
     - `200`: List of blog posts
     - `500`: Server error

3. **Get Single Blog Post by ID**
   - Method: `GET`
   - Endpoint: `/api/v1/blog/{id}`
   - Description: Allow a user to get a single post by ID.
   - Parameters:
     - `id`: string (required)
   - Responses:
     - `200`: Blog post details
     - `404`: Blog post not found
     - `500`: Server error

4. **Edit Blog Post by ID**
   - Method: `PUT`
   - Endpoint: `/api/v1/blog/{id}`
   - Description: Allow an author to edit a blog post by ID.
   - Parameters:
     - `id`: string (required)
   - Request Body:
     ```yaml
     BlogInput:
       type: object
       properties:
         title:
           type: string
           description: Title of the blog post
         content:
           type: string
           description: Content of the blog post
         author:
           type: string
           description: Author of the blog post
         categories:
           type: array
           items:
             type: string
           description: Categories of the blog post
         Imageurl:
           type: string
           description: URL of the blog post image
         tags:
           type: array
           items:
             type: string
           description: Tags of the blog post
       required:
         - title
         - content
         - author
     ```
   - Responses:
     - `200`: Blog post updated successfully
     - `400`: Bad request
     - `404`: Blog post not found
     - `500`: Server error

5. **Delete Blog Post by ID**
   - Method: `DELETE`
   - Endpoint: `/api/v1/blog/{id}`
   - Description: Allow an author to delete a blog post by ID.
   - Parameters:
     - `id`: string (required)
   - Responses:
     - `204`: Blog post deleted successfully
     - `404`: Blog post not found
     - `500`: Server error

**Schema:**
```yaml
components:
  schemas:
    Blog:
      type: object
      properties:
        title:
          type: string
          description: Title of the blog post
        content:
          type: string
          description: Content of the blog post
        author:
          type: string
          description: Author of the blog post
        categories:
          type: array
          items:
            type: string
          description: Categories of the blog post
        Imageurl:
          type: string
          description: URL of the blog post image
        tags:
          type: array
          items:
            type: string
          description: Tags of the blog post
        likes:
          type: integer
          description: Number of likes on the blog post
        comments:
          type: array
          items:
            type: object
            properties:
              author:
                type: string
                description: Author of the comment
              content:
                type: string
                description: Content of the comment
              created_at:
                type: string
                format: date-time
                description: Timestamp of when the comment was created
        created_at:
          type: string
          format: date-time
          description: Creation timestamp of the blog post
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp of the blog post

    BlogInput:
      type: object
      properties:
        title:
          type: string
          description: Title of the blog post
        content:
          type: string
          description: Content of the blog post
        author:
          type: string
          description: Author of the blog post
        categories:
          type: array
          items:
            type: string
          description: Categories of the blog post
        Imageurl:
          type: string
          description: URL of the blog post image
        tags:
          type: array
          items:
            type: string
          description: Tags of the blog post
      required:
        - title
        - content
        - author
```

**Acceptance Criteria:**
- A Swagger (OpenAPI) document is created that includes all the above endpoints.
- Each endpoint must have a detailed description, request parameters, request body (if applicable), and responses.
- The document should be well-structured and follow OpenAPI specifications.

**Additional Information:**
Refer to the existing API implementations for accurate endpoint details and data structures.

**Assignees:**
- Devffery

**Labels:**
- `documentation`
- `API`
- `swagger`
- `OpenAPI`
