### ISSUE TITLE
Admin Route Documentation

### ISSUE THREAD

**Issue by ememuo** [hngprojects/hng_boilerplate_expressjs#194]
### **Description:**

Documentation for Admin routes. This will help developers understand and use our API endpoints more effectively.

Method: `PATCH`
Endpoint:` /api/v1/admin`
Description: Updates the details of an existing organisation.

Parameters:
`id`: string (required)

Request Body:
```
required: true
content:
     application/json:
         schema:
             type: object
             properties: 
                 name:
                    type: string
                  address: 
                    type: string
                   phone: 
                    type: string
```

Responses:
`200`: The organisation was successfully updated, content(id, name, address, phone)
`400`: Bad request
`404`: Organisation not found
`401`: Unauthorized
`403`: Forbidden

### 
**Acceptance Criteria:**

Swagger documentation annotations added to all routes in the admin.ts file.
Documentation includes descriptions, parameters, request bodies, and responses.
Ensure the Swagger documentation is properly displayed in the Swagger UI.

Assignees:

- Angel Muo
